"use client";

import React, { useState, useTransition, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ShieldCheck, Smartphone, Key } from "lucide-react";
import { AuthFormContainer } from "@/components/dashboard/auth/AuthFormContainer";
import { OtpInput } from "@/components/dashboard/auth/OtpInput";
import { AuthInput } from "@/components/dashboard/auth/AuthInput";
import { AuthAlert } from "@/components/dashboard/auth/AuthAlert";
import { AuthSubmitButton } from "@/components/dashboard/auth/AuthSubmitButton";
import { verifyAdminMfaAction } from "@/lib/actions/dashboard-auth.actions";

function MfaVerificationContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const email = searchParams.get("email") || "";
  const returnUrl = searchParams.get("returnUrl") || "/dashboard";

  const [useRecoveryCode, setUseRecoveryCode] = useState(false);
  const [totpCode, setTotpCode] = useState("");
  const [recoveryCode, setRecoveryCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    const code = useRecoveryCode ? recoveryCode.trim() : totpCode.trim();
    if (!code) {
      setError(useRecoveryCode ? "Please enter your recovery backup code." : "Please enter the 6-digit code from your authenticator app.");
      return;
    }

    const formData = new FormData();
    formData.append("email", email);
    formData.append("code", code);
    formData.append("isRecovery", String(useRecoveryCode));

    startTransition(async () => {
      const res = await verifyAdminMfaAction(formData);
      if (!res.success) {
        setError(res.error || "The verification code is incorrect.");
      } else {
        router.push(returnUrl);
        router.refresh();
      }
    });
  };

  return (
    <AuthFormContainer
      title="Two-Factor Authentication"
      subtitle={
        useRecoveryCode
          ? "Enter one of your emergency 8-character backup recovery codes."
          : "Enter the 6-digit verification code generated by your Authenticator app (Google Authenticator, Microsoft Authenticator, or 1Password)."
      }
      backHref="/dashboard/login"
      backLabel="Cancel & Return to Login"
    >
      {error && <AuthAlert type="ERROR" message={error} />}

      <form onSubmit={handleVerify} className="space-y-5">
        {!useRecoveryCode ? (
          <div className="space-y-2">
            <div className="flex items-center justify-center gap-1.5 text-xs text-[#0088cc] font-semibold mb-1">
              <Smartphone className="w-4 h-4" />
              <span>Time-based One-Time Password (TOTP)</span>
            </div>
            <OtpInput value={totpCode} onChange={setTotpCode} error={Boolean(error)} disabled={isPending} />
          </div>
        ) : (
          <div className="space-y-2">
            <AuthInput
              label="Emergency Recovery Code"
              type="text"
              required
              value={recoveryCode}
              onChange={(e) => setRecoveryCode(e.target.value)}
              placeholder="e.g. A1B2-C3D4"
              icon={<Key className="w-4 h-4" />}
            />
          </div>
        )}

        <div className="flex items-center justify-between text-xs text-[#647581] pt-1">
          <button
            type="button"
            onClick={() => {
              setUseRecoveryCode(!useRecoveryCode);
              setError(null);
            }}
            className="text-[#0088cc] font-semibold hover:underline cursor-pointer"
          >
            {useRecoveryCode ? "Use Authenticator App code" : "Lost access? Use Recovery Code"}
          </button>
        </div>

        <div className="pt-2">
          <AuthSubmitButton isLoading={isPending} icon={<ShieldCheck className="w-4 h-4 shrink-0" />}>
            Verify Authentication
          </AuthSubmitButton>
        </div>
      </form>
    </AuthFormContainer>
  );
}

export default function DashboardMfaPage() {
  return (
    <Suspense fallback={<div className="p-8 text-center text-xs text-[#647581]">Loading MFA verification...</div>}>
      <MfaVerificationContent />
    </Suspense>
  );
}
